### ISSUE TITLE
Menu not expanding

### ISSUE THREAD

**Issue by migueacastro** [dhruv8sh/arch-update-checker#12] opened 2024-03-24 23:06 UTC
Recently installed it with the commands provided. It's added to the panel but it's not expanding when clicked

![image](https://github.com/dhruv8sh/arch-update-checker/assets/54249734/0347a79f-b242-488d-8cab-e726a741a961)

**Comment by dhruv8sh** [comment] 2024-03-25 00:11
Closing for being a duplicate of #11.

**Closed** 2024-03-25 00:11 UTC

**Comment by dhruv8sh** [comment] 2024-03-25 03:19
Should be fixed in the latest commit. See #11 for more details.
