### ISSUE TITLE
[Question] Horizontal scrollbar

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#30] opened 2024-04-07 18:45 UTC
I just wanna ask, why is there a horizontal scrollbar sometimes at the bottom of the widget, like in this picture from the readme:
https://private-user-images.githubusercontent.com/67322047/319741581-c5d726d4-a769-4dba-918b-06e921650e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTU2MDYsIm5iZiI6MTcxMjUxNTMwNiwicGF0aCI6Ii82NzMyMjA0Ny8zMTk3NDE1ODEtYzVkNzI2ZDQtYTc2OS00ZGJhLTkxOGItMDZlOTIxNjUwZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE4NDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMzRlMzQ2NjYzZWY5OTFiZDUyOTIyMzJmNGUyY2EzOTE4NjVjZjJkYWM0ZmUwYzkxZWE4Y2ZkNTRiOGNiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91WXvYeq_dyYQZEQ8nMJYH8b86hWgTJ_WvcDlq3oBuU

**Comment by Kingproone** [comment] 2024-04-08 13:34
since the above link broke:
![image](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/fdb752c1-2858-40d4-828e-768e07dcfb88)

**Comment by dhruv8sh** [comment] 2024-04-08 14:19
Yes this was reproducible. Turns out when the ScrollView tries to draw a Vertical Scrollbar it miscalculates margins by 1px. Hence, the horizontal scrollbar. Next release is today. It will be fixed in that.

**Comment by dhruv8sh** [comment] 2024-04-08 18:12
Fixed!

**Closed by dhruv8sh** 2024-04-08 18:12 UTC

**Comment by dhruv8sh** [comment] 2024-05-23 11:40
I'll make the download size so that it does not show up when it's NaN, undefined or whatever.

**Comment by Kingproone** [comment] 2024-05-23 11:43
It probably bugged, because I only had AUR updates.

**Comment by dhruv8sh** [comment] 2024-05-23 11:45
That should not matter, since all the information is fetched from 'pacinfo'.

**Comment by Kingproone** [comment] 2024-05-23 11:46
> The horizontal scrollbar does not exist for me...
It may be, because when I changed the pause unpause, the vertical scrollbar appeared and that update trips it up somehow
>That should not matter, since all the information is fetched from `pacinfo`.
weird

**Comment by dhruv8sh** [comment] 2024-05-23 11:48
Can you test the latest commit for the scrollbar fix?

**Comment by Kingproone** [comment] 2024-05-23 11:51
[Screencast_20240523_135056.webm](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/0d90efa3-c7c1-4b60-9d82-62cada3b1be1)

**Comment by dhruv8sh** [comment] 2024-05-23 11:52
Did you run ```systemctl --user restart plasma-plasmashell``` after updating?

**Comment by Kingproone** [comment] 2024-05-23 11:55
[Screencast_20240523_135427.webm](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/9869b04a-7d53-41b0-8763-f18c6e9aa23f)

 it doesn't trigger no more (after the restart), but at the buttom says 0, when only aur is left
